<?php
// $Id: nodetypeviews.module,v 1.3 2008/08/30 22:54:39 yaph Exp $

/**
 * @file
 * Creates teaser views and RSS feeds for published content by node type.
 */

/**
 * Implemetation of hook_menu().
 */
function nodetypeviews_menu() {
  $items = array();
  $items['admin/content/nodetypeviews'] = array(
    'title' => 'Node Type Views',
    'description' => 'Enable the node types to generate views for.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodetypeviews_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'nodetypeviews.admin.inc'
  );
  $node_types = variable_get('nodetypeviews_node_types', array());
  if (is_array($node_types)) {
    foreach ($node_types as $type => $isset) {
      if ($isset) {
        $path = str_replace('_', '-', $type);
        $title = ucfirst($type);
        $items[$path] = array(
          'title' => $title,
          'access arguments' => array('access content'),
          'type' => MENU_NORMAL_ITEM,
          'page callback' => 'nodetypeviews_type_teaser_view',
          'page arguments' => array($type),
          'file' => 'nodetypeviews.pages.inc'
        );
        $items[$path .'/feed'] = array(
          'title' => $title,
          'access arguments' => array('access content'),
          'type' => MENU_CALLBACK,
          'page callback' => 'nodetypeviews_type_teaser_feed',
          'page arguments' => array($type),
          'file' => 'nodetypeviews.pages.inc'
        );
      }
    }
  }
  return $items;
}